Just a dev notebook to develop the algorithm. Will export the finals into a py file for execution. 

In [ ]:
# Import the data
import pandas as pd
from utils.data_loading import load_participant_details

participant_details = load_participant_details('./raw_data/participant_details.xlsx')

participant = participant_details[0]
path = participant['filename']
data = pd.read_csv(f'./raw_data/{path}', sep='\t')

In [ ]:
# sum humerothoracic motion

import numpy as np
import numpy.typing as npt
import pandas as pd

def extract_rotation_matrix(row: pd.Series, arm: str) -> np.ndarray:
    """Extract a 3x3 rotation matrix from a data row.

    Extracts the nine rotation matrix elements for the specified arm from
    a row of motion capture data and returns them as a 3x3 NumPy array.

    Args:
        row (pd.Series): A row from the motion capture data DataFrame.
        arm (str): Arm identifier, either 'L' (left) or 'R' (right).

    Returns:
        np.ndarray: A 3x3 rotation matrix with shape (3, 3).

    Raises:
        ValueError: If arm is not 'L' or 'R'.
        KeyError: If required matrix columns are missing from the row.

    Example:
        >>> row_data = pd.Series({'L00': 0.1, 'L01': -0.37, ..., 'L22': 0.41})
        >>> R = extract_rotation_matrix(row_data, 'L')
        >>> R.shape
        (3, 3)
    """
    if arm not in ['L', 'R']:
        raise ValueError(f"arm must be 'L' or 'R', got {arm}")

    # Column names for the rotation matrix elements
    columns = [f'{arm}{i}{j}' for i in range(3) for j in range(3)]

    try:
        values: npt.NDArray[np.float64] = np.array(row[columns].values, dtype=np.float64)
    except KeyError as e:
        raise KeyError(f"Missing rotation matrix columns for arm {arm}: {e}")

    # Reshape into 3x3 matrix
    return values.reshape(3, 3)
a=extract_rotation_matrix(data.iloc[1], 'L')
print(a)

[[ 0.112   0.0841  0.9901]
 [-0.1202  0.9902 -0.0705]
 [-0.9864 -0.1111  0.1211]]


In [ ]:
# extract the filename, arm, and handedness
# for each arm
    # sum humerothoracic rotation
    # sum glenoohumeral rotation (later)
    # bin %time spent in each region of elevation and PoE